import java.util.Random;

public class AccountNumber implements Comparable<AccountNumber> {
    private static final int SEED = 9999; //for a fix sequence of random numbers.
    private Branch branch;
    private AccountType type;
    private String number; //a 4-digit number generated by the Random object

    public AccountNumber(Branch branch, AccountType type, String number) {
        this.branch = branch;
        this.type = type;
        this.number = generateAccountNumber();
    }

    private String generateAccountNumber() {
        Random random = new Random(SEED);
        int num = random.nextInt(10000);
        return String.format("%04d", num);
    }

    @Override
    public int compareTo(AccountNumber other) {
        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Branch) {
            AccountNumber other = (AccountNumber) obj;
            return this.branch.equals(other.branch) && this.type.equals(other.type) && this.number.equals(other.number);
        }
        return false;
    }

    @Override
    public String toString() {
        return branch.toString() + type.toString() + number;
    }


}
