import java.util.Random;

public class AccountNumber implements Comparable<AccountNumber> {
    private static final int SEED = 9999; //for a fix sequence of random numbers.
    private Branch branch;
    private AccountType type;
    private String number; //a 4-digit number generated by the Random object

    public AccountNumber(Branch branch, AccountType type, String number) {
        this.branch = branch; //class with zip, branchcode, and county
        this.type = type;     //class with type of account
        this.number = generateAccountNumber(); //random 4 digit number
    }

    private String generateAccountNumber() {
        Random random = new Random(SEED);
        int num = random.nextInt(10000);
        return String.format("%04d", num);
    }

    @Override
    public int compareTo(AccountNumber other) {
        return this.number.compareTo(other.number);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Branch) {
            AccountNumber other = (AccountNumber) obj;
            return this.branch.equals(other.branch) && this.type.equals(other.type) && this.number.equals(other.number);
        }
        return false;
    }

    @Override
    public String toString() {
        return branch.toString() + type.toString() + number;
    }

}
