import java.util.Random;

public class AccountNumber implements Comparable<AccountNumber> {
    private static final int SEED = 9999; //for a fix sequence of random numbers.
    private src.Branch branch;
    private src.AccountType type;
    private String number; //a 4-digit number generated by the Random object

    @Override
    public int compareTo(AccountNumber o) {
        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Branch) {
            Branch branch = (Branch) obj;
            if (
                this.zip.equals(branch.zip) &&
                this.branchCode.equals(branch.branchCode) &&
                this.county.equals(branch.county)
            ) return true;
        } else if (obj instanceof AccountType) {
            AccountType accType = (AccountType) obj;
            if (this.code.equals(accType.code)) return true;
        }
        return false;
    }
    public int getSeed () {
        return SEED;
    }
    public void generateSeed() {
        Random rnd = new Random();
        rnd.setSeed(SEED);
    }
}
